# meta
title: 个人博客
email: yunxiao141@foxmail.com
description: "这个网站是一个博客网站,基于Jekyll,开始于2023/06/18 17:00"
baseurl: ""
url: "https://red352.github.io"
github_username: red352
lang: zh
disqus:
  shortname: red352
footer_menu: footer_menu

# theme_color: hsl(0, 0%, 29%)
# theme: minima
# theme: bulma-clean-theme
permalink: pretty
remote_theme: chrisrhymes/bulma-clean-theme # for github pages

# 分页
paginate: 10
paginate_path: "/blog/page:num"

# 默认参数
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      author: "red352"
      layout: post
      # image: https://avatars.githubusercontent.com/u/54206379?v=4
      show_sidebar: true
      comments: true # open comments

# 插件
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-paginate
  - jekyll-sitemap
